# Generated by Django 5.2.5 on 2025-08-31 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0002_business_userprofile_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_type', models.CharField(choices=[('human', 'Human Life'), ('yearly', 'Yearly'), ('business', 'Business'), ('health', 'Health'), ('daily', 'Daily'), ('soul', 'Soul'), ('reincarnation', 'Reincarnation')], max_length=20)),
                ('period_number', models.IntegerField()),
                ('description', models.TextField()),
                ('effects', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='other_dates',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.CreateModel(
            name='UserCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_type', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('current_period', models.IntegerField()),
                ('report_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycles.userprofile')),
            ],
        ),
    ]
